version: '3.8'

services:
    client:
        container_name: web-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        # depends_on:
        #     - postgres
        #     - server
        ports:
            - '1337:80'
        # networks:
        #     - postgres